apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: newsletter-ui.newsletter-gitops.vmware.com.20231223163826.0.0+build.1c32140
spec:
  refName: newsletter-ui.newsletter-gitops.vmware.com
  version: 20231223163826.0.0+build.1c32140
  releaseNotes: |
    Release v20231223163826.0.0+build.1c32140 of package newsletter-ui.newsletter-gitops.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.apps.tap.tanzudemohub.com/tap-supply-chain-basic/newsletter-ui-newsletter-gitops-bundle@sha256:a59d81c53cb64e81ce1c21a96ea8508e77091a926633594c443a361a32a9e705
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

