apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: newsletter-ui.newsletter.vmware.com.20231220120554.0.0+build.1c32140
spec:
  refName: newsletter-ui.newsletter.vmware.com
  version: 20231220120554.0.0+build.1c32140
  releaseNotes: |
    Release v20231220120554.0.0+build.1c32140 of package newsletter-ui.newsletter.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.apps.tapmc.tanzudemohub.com/tap-supply-chain-basic/newsletter-ui-newsletter-bundle@sha256:a2e4cec65972f06bccb77cfe2bea93141f0cb8a2a9ad291e8afe62d74f8eeb42
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

