apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: newsletter-ui.newsletter.vmware.com.20231220000956.0.0+build.1c32140
spec:
  refName: newsletter-ui.newsletter.vmware.com
  version: 20231220000956.0.0+build.1c32140
  releaseNotes: |
    Release v20231220000956.0.0+build.1c32140 of package newsletter-ui.newsletter.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.apps.tapmc.tanzudemohub.com/tap-supply-chain-basic/newsletter-ui-newsletter-bundle@sha256:07f565d0216cd9fbfed175cb0ebdb68aaf1504f1051cc6c88c2a89408cda0e3d
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

