apiVersion: kapp.k14s.io/v1alpha1
kind: Config
waitRules:
- conditionMatchers:
  - type: ServiceAvailable
    status: "False"
    failure: true
  - type: ServiceAvailable
    status: "True"
    success: true
  resourceMatchers:
  - apiVersionKindMatcher:
      apiVersion: servicebinding.io/v1alpha3
      kind: ServiceBinding
---
apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: newsletter-subscription-db
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"carto.run/v1alpha1","kind":"Workload","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"newsletter","apps.tanzu.vmware.com/workload-type":"web"},"name":"newsletter-subscription","namespace":"newsletter-regops"},"spec":{"build":{"env":[{"name":"BP_JVM_VERSION","value":"20"}]},"params":[{"name":"gitops_ssh_secret","value":"github-ssh-secret"},{"name":"gitops_server_address","value":"https://github.com/"},{"name":"gitops_repository_owner","value":"sdubois-tapdemo"},{"name":"gitops_repository_name","value":"cartographer"}],"serviceClaims":[{"name":"db","ref":{"apiVersion":"services.apps.tanzu.vmware.com/v1alpha1","kind":"ClassClaim","name":"newsletter-db"}}],"source":{"git":{"ref":{"branch":"main"},"url":"https://github.com/sdubois-tapdemo/newsletter"},"subPath":"newsletter-subscription"}}}
    kapp.k14s.io/change-group: servicebinding.io/ServiceBindings
  labels:
    app.kubernetes.io/part-of: newsletter
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: newsletter-subscription
spec:
  name: db
  service:
    apiVersion: services.apps.tanzu.vmware.com/v1alpha1
    kind: ClassClaim
    name: newsletter-db
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: newsletter-subscription

