apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: newsletter-subscription.newsletter.vmware.com.20231213191826.0.0+build.2361c5c
spec:
  refName: newsletter-subscription.newsletter.vmware.com
  version: 20231213191826.0.0+build.2361c5c
  releaseNotes: |
    Release v20231213191826.0.0+build.2361c5c of package newsletter-subscription.newsletter.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.apps.tapmc.tanzudemohub.com/tap-supply-chain-basic/newsletter-subscription-newsletter-bundle@sha256:e1756f1516465690d5641f1a44703e3a2ff3eebbfa155af57d38e30d6f56bf12
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

