apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: newsletter-subscription.newsletter.vmware.com.20231212183657.0.0+build.c09d0eb
spec:
  refName: newsletter-subscription.newsletter.vmware.com
  version: 20231212183657.0.0+build.c09d0eb
  releaseNotes: |
    Release v20231212183657.0.0+build.c09d0eb of package newsletter-subscription.newsletter.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.apps.tapmc.tanzudemohub.com/tap-supply-chain-basic/newsletter-subscription-newsletter-bundle@sha256:973612b36a09a737f3ee0515c7c727ff24c9b52c14a8aa135d21005738c6f720
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

