apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: newsletter-subscription.newsletter.vmware.com.20231220155304.0.0+build.1c32140
spec:
  refName: newsletter-subscription.newsletter.vmware.com
  version: 20231220155304.0.0+build.1c32140
  releaseNotes: |
    Release v20231220155304.0.0+build.1c32140 of package newsletter-subscription.newsletter.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.apps.tapmc.tanzudemohub.com/tap-supply-chain-basic/newsletter-subscription-newsletter-bundle@sha256:22845952e779ad220cfc3f082d8a80d97465a152ee02c93f8730425a90b5e20c
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

