apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: newsletter-subscription.newsletter.vmware.com.20231214110241.0.0+build.c0a90c3
spec:
  refName: newsletter-subscription.newsletter.vmware.com
  version: 20231214110241.0.0+build.c0a90c3
  releaseNotes: |
    Release v20231214110241.0.0+build.c0a90c3 of package newsletter-subscription.newsletter.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.apps.tapmc.tanzudemohub.com/tap-supply-chain-basic/newsletter-subscription-newsletter-bundle@sha256:0f0055c26488db1b42ce19c09e21ac037d9b11a2c375fdc17231db07b48e2c71
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

