apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: newsletter-subscription.newsletter.vmware.com.20231222225155.0.0+build.1c32140
spec:
  refName: newsletter-subscription.newsletter.vmware.com
  version: 20231222225155.0.0+build.1c32140
  releaseNotes: |
    Release v20231222225155.0.0+build.1c32140 of package newsletter-subscription.newsletter.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.apps.tap.tanzudemohub.com/tap-supply-chain-basic/newsletter-subscription-newsletter-bundle@sha256:75e2ca0e1fd79060991c4875f5c8e0ca42cb9f8e6dbe0405ac7496e3a98d7ee9
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

