apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: newsletter-subscription.newsletter.vmware.com.20231219201425.0.0+build.51f72c4
spec:
  refName: newsletter-subscription.newsletter.vmware.com
  version: 20231219201425.0.0+build.51f72c4
  releaseNotes: |
    Release v20231219201425.0.0+build.51f72c4 of package newsletter-subscription.newsletter.vmware.com
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.apps.tapmc.tanzudemohub.com/tap-supply-chain-basic/newsletter-subscription-newsletter-bundle@sha256:2b8fa6947c61db8dbfaec706a5f854e1c752a924e79a027aab5a3b6316f492bf
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

